export const colors = {
  "gray-light": {
    "25": {
      description: "",
      type: "color",
      value: "#fcfcfdff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#f9fafbff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#f2f4f7ff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#e4e7ecff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#d0d5ddff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#98a2b3ff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#667085ff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#475467ff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#344054ff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#182230ff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#101828ff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#0c111dff",
      blendMode: "normal",
    },
  },
  "gray-dark": {
    "25": {
      description: "",
      type: "color",
      value: "#fafafaff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#f5f5f6ff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#f0f1f1ff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#ececedff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#cecfd2ff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#94969cff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#85888eff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#61646cff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#333741ff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#1f242fff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#161b26ff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#0c111dff",
      blendMode: "normal",
    },
  },
  brand: {
    "25": {
      description: "",
      type: "color",
      value: "#fcfaffff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#eef6ffff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#daeaffff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#bddbffff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#90c5ffff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#5ba4ffff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#3581fcff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#1e61f2ff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#174bdeff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#1738a4ff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#1a388eff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#152456ff",
      blendMode: "normal",
    },
  },
  error: {
    "25": {
      description: "",
      type: "color",
      value: "#fffbfaff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#fef3f2ff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#fee4e2ff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#fecdcaff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#fda29bff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#f97066ff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#f04438ff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#d92d20ff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#b42318ff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#912018ff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#7a271aff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#55160cff",
      blendMode: "normal",
    },
  },
  warning: {
    "25": {
      description: "",
      type: "color",
      value: "#fffcf5ff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#fffaebff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#fef0c7ff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#fedf89ff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#fec84bff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#fdb022ff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#f79009ff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#dc6803ff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#b54708ff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#93370dff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#7a2e0eff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#4e1d09ff",
      blendMode: "normal",
    },
  },
  success: {
    "25": {
      description: "",
      type: "color",
      value: "#f6fef9ff",
      blendMode: "normal",
    },
    "50": {
      description: "",
      type: "color",
      value: "#ecfdf3ff",
      blendMode: "normal",
    },
    "100": {
      description: "",
      type: "color",
      value: "#dcfae6ff",
      blendMode: "normal",
    },
    "200": {
      description: "",
      type: "color",
      value: "#abefc6ff",
      blendMode: "normal",
    },
    "300": {
      description: "",
      type: "color",
      value: "#75e0a7ff",
      blendMode: "normal",
    },
    "400": {
      description: "",
      type: "color",
      value: "#47cd89ff",
      blendMode: "normal",
    },
    "500": {
      description: "",
      type: "color",
      value: "#17b26aff",
      blendMode: "normal",
    },
    "600": {
      description: "",
      type: "color",
      value: "#079455ff",
      blendMode: "normal",
    },
    "700": {
      description: "",
      type: "color",
      value: "#067647ff",
      blendMode: "normal",
    },
    "800": {
      description: "",
      type: "color",
      value: "#085d3aff",
      blendMode: "normal",
    },
    "900": {
      description: "",
      type: "color",
      value: "#074d31ff",
      blendMode: "normal",
    },
    "950": {
      description: "",
      type: "color",
      value: "#053321ff",
      blendMode: "normal",
    },
  },
};
